#!/bin/bash

version="$1"

if [ "" == "$version" ]
then
    version="stable"
fi

target=$(curl -s https://hnhdigital-os.github.io/fs-deploy/$version)

curl -o ./fs-deploy -LSs https://hnhdigital-os.github.io/fs-deploy/download/$target/fs-deploy.phar
chmod 755 ./fs-deploy
