#!/bin/bash

version="$1"

if [ "" == "$version" ]
then
    version="stable"
fi

target=$(curl -s https://hnhdigital-os.github.io/git-deploy/$version)

curl -o ./git-deploy -LSs https://hnhdigital-os.github.io/download/$target/git-deploy.phar
chmod 755 ./git-deploy
